---
title: "22-05-02-Country-Data-Prep"
author: "Matt Shu"
date: "`r Sys.Date()`"
output: pdf_document
---

## Preprocessing
Note: 
```{r}
conn <- dbConnect(RSQLite::SQLite(), "../files/22-04-21-playback-fm-top-country.db")
dfSongs <- dbGetQuery(conn, 'SELECT * FROM lyrics')
dfArtists <- dbGetQuery(conn, 'SELECT * FROM artists')
```

## Dataset Visualizations
There are some duplicate songs for those who charted multiple years. Remove those songs
```{r}
dim(dfSongs)
dfSongs <- distinct(dfSongs, artist, track, .keep_all = TRUE)
dim(dfSongs)
```
Turn "nan" into NA's and select only variables of interest
```{r}
dfArtists[dfArtists == "nan"] <- NA
dfArtistsInterest <- dfArtists %>%
   dplyr::select(artist_id, mb_id, type, area.name, gender, life_span.begin, life_span.ended) %>%
   # the objects need to be class "data frame" 
   as.data.frame()
```

```{r}
dfSongsArtists <- merge(dfSongs,dfArtistsInterest,by="artist_id")
```

```{r Remove Missing}
cleaned_df <-dfSongsArtists %>%
  # first, remove observation with missing values of the meta variables
  filter(!is.na(lyrics))  %>%
  # first, remove observation with missing values of the meta variables
  filter(!is.na(artist))  %>%
  as.data.frame()
cleaned_df$lyrics <- str_replace_all(cleaned_df$lyrics,"[\\s]+", " ")
```
## Create ID Hashes
```{r}
# cleaned_df$artist_id <- as.character(as.numeric(as.factor(cleaned_df$artist)))
cleaned_df$song_id <- as.character((10000 + as.numeric(as.factor(cleaned_df$track))))
```

## Filter out Mismatches

```{r Remove Erroneous Lyrics}
dim(cleaned_df)
cleaned_df$cleaned_lyrics <- 
  str_replace_all(cleaned_df$lyrics, 'Chap\\. [0-9]', NA_character_) %>%
  str_replace_all(., 'Listening Log', NA_character_) %>%
  str_replace_all(., 'Favorite Songs Of', NA_character_) %>%
  str_replace_all(., 'Chapter [0-9]', NA_character_) %>%
  str_replace_all(., 'New Music ', NA_character_) %>%
  str_replace_all(., 'Nominees', NA_character_) %>%
  str_replace_all(., 'Best Songs of ', NA_character_) %>%
  str_replace_all(., "[0-9]+ U S", NA_character_) %>% # Court Cases
  str_replace_all(.,"[ ]+", " ") %>%
  str_replace(., ".*Lyrics", "")
cleaned_df <- cleaned_df %>%
  filter(!is.na(cleaned_lyrics)) %>%
  filter(levenshteinSim(track, str_match(lyrics, "(.*)Lyrics")[,2]) > .5) %>% # There are some false positives, when there are other languages
  as.data.frame()
dim(cleaned_df)
cleaned_df$lyrics_alnum <- cleaned_df$cleaned_lyrics %>% str_replace_all(., "[^[:alnum:]]", " ")
```

```{r}
cleaned_df <- cleaned_df %>% 
    mutate(gender = replace(gender, gender == "other", "non-binary")) %>% 
    mutate(gender = replace(gender, is.na(gender), "unknown"))
```


```{r}
cleaned_df <- cleaned_df %>% select(-c(level_0, index))
```

## Export Cleaned
```{r}
dbWriteTable(conn, "cleaned", cleaned_df, overwrite=TRUE)
dbDisconnect(conn)
```

