---
title: "Country Music Project"
author: "Matt Shu"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Prereqs

```{r}
library(stm)
library(tidyverse)
# library(DBI)
library(RSQLite)
```


## Preprocessing
```{r}
conn <- dbConnect(RSQLite::SQLite(), "files/country_song_project.db")
dfSongs <- dbGetQuery(conn, 'SELECT * FROM songs')
dfLyrics <- dbGetQuery(conn, 'SELECT * FROM lyrics')
dfWords <- dbGetQuery(conn, 'SELECT * FROM Words')
dbDisconnect(conn)
```

## Dataset Visualizations
### Year
```{r}
# shs represents wheter a song is a cover
dfSongs$year[dfSongs$year == 0] <- NA
str(dfSongs$year)
summary(dfSongs$year)
hist(dfSongs$year, main="", xlab="Year")
axis(side=1, at=seq(1920, 2010, by=10))
```
### Duration
```{r}
dfSongs$duration[dfSongs$duration < 10] <- NA
str(dfSongs$duration)
summary(dfSongs$duration)
hist(dfSongs$duration, main="Country Track Length", xlab="Duration (Seconds)")
```
### Artist Familiarity vs Year
```{r}
plot(dfSongs$year, dfSongs$artist_hotttnesss)
```

## Dictionary Methods
```{r}
# Alcohol
alcoholWords <- c("alcohol", "beer", "whiskey", "rum", "tequila")

# Love
loveWords <- c("love", "forever", "babe")
# Patriotism
america <- c("america", "american", "countri") #maybe also counti for county?
# Feelings
feelings <- c("dream", "hope", "sad", "tear")
# Country Songs about Country
songsAboutCountry <- c("country", "dirt", "road", "truck")
# Anger
cursing <- c("fuck", "sin", "shit", "bullshit", "hell", "sinner", "goddamn", "ass")
# Religion
religious <- c("jesus", "christ", "god", "love")

# Other words
romance <- c("girl", "beer")
```
### Counts
```{r}
dictAlc <- "alcohol|beer|whiskey|rum|tequila"
dictRel <- "jesus|christ|god"
dictCurse <- "fuck|sin|shit|bullshit|hell|sinner"
```
### Functions
```{r}
filter_years <- function(df, start, end) {
   return(df %>% filter(year >= start) %>% filter(year < end))
}
filter_lyrics <- function(dfLyrics, dfSongs) {
  return(dfLyrics %>% filter(track_id %in% dfSongs$track_id))
}
filter_for_dict <- function(dfLyrics, dict) {
  return(dfLyrics %>% filter(word %in% dict))
}
```

### Subyears
```{r}
df00_10 <- filter_years(dfSongs, 2000, 2011) # One extra year
df90_00 <- filter_years(dfSongs, 1990, 2000)
df80_90 <- dfSongs %>% filter(year < 1990) %>% filter(year >= 1980)
df70_80 <- dfSongs %>% filter(year < 1980) %>% filter(year >= 1970)
df60_70 <- dfSongs %>% filter(year < 1970) %>% filter(year >= 1960)

df00_10_lyrics <- filter_lyrics(dfLyrics, df00_10)
df90_00_lyrics <- filter_lyrics(dfLyrics, df90_00)
df80_90_lyrics <- filter_lyrics(dfLyrics, df80_90)
df70_80_lyrics <- filter_lyrics(dfLyrics, df70_80)
df60_70_lyrics <- filter_lyrics(dfLyrics, df60_70)
```
### Count
```{r}
df00_10_alcohol <- filter_for_dict(df00_10_lyrics, alcoholWords)
df90_00_alcohol <- filter_for_dict(df90_00_lyrics, alcoholWords)
df80_90_alcohol <- filter_for_dict(df80_90_lyrics, alcoholWords)

plot_df <- dplyr::tibble(
  dict = c("2000s-10s", "1990-00s", "1980-90s"),
  count = c(sum(df00_10_alcohol$count)/length(df00_10),
            sum(df90_00_alcohol$count)/length(df90_00),
            sum(df80_90_alcohol$count)/length(df80_90))
)
```

### Graphs
```{r fig.retina=3, fig.height=4}
library(ggplot2)
ggplot(plot_df, aes(y = count, x = dict, fill = dict)) +
  geom_bar(stat = "identity") +
  labs(y = "Prevalence", x = ' ', fill = "Dictionary") +
   theme(aspect.ratio = 0.75) +
   theme(axis.text = element_text(size = 16),
        axis.title = element_text(size = 16),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16))
```

## Topic Models
```{r}
# dfNewSongs <- dfLyrics %>%
# mutate(weighted_string = rep(word, count)) %>% # this is where we multiply the words by their counts to create a weighted string
# group_by(track_id) %>%
# mutate(track_words = paste(weighted_string, collapse = " ")) %>% # paste each track's strings together
# distinct() %>% # remove multiple observations of the same track
# ungroup()
```

## Other ideas
Another idea might be to evaluate the difference between third person and non-third person songs
