---
title: "quanteda_analyses"
author: "Matt Shu"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Prereqs

```{r}
library(tidyverse)
library(RSQLite)
library(quanteda)
library(quanteda.textstats)
library(car)
source("http://www.reuningscherer.net/s&ds230/Rfuncs/regJDRS.txt")
```

## Load Dataset
```{r}
conn <- dbConnect(RSQLite::SQLite(), "files/22-04-21-playback-fm-top-country.db")
cleaned_df <- dbGetQuery(conn, 'SELECT * FROM cleaned')
dbDisconnect(conn)
```

```{r}
cleaned_corpus <- corpus(
  cleaned_df,
  docid_field = "track_id",
  text_field = "cleaned_lyrics",
  unique_docnames = TRUE
)
```

```{r}
toks <- tokens(cleaned_corpus, remove_punct=T, remove_symbols=T, remove_numbers=T, remove_separators=T)
country_dfm <- dfm(toks)
tstat_lexdiv <- textstat_lexdiv(country_dfm, measure="TTR")

cleaned_df <- merge(cleaned_df,tstat_lexdiv, by.x = "track_id",by.y="document")
tail(tstat_lexdiv, 5)
year_df <- cleaned_df %>%
  group_by(year) %>%
  summarize(TTR = mean(TTR))
```

```{r}
pdf(file = "figures/lex-div-over-time.pdf", width = 4, height = 3)
ggplot(year_df, aes(x = year, y = TTR)) +
  geom_point() +
  geom_smooth(method = "gam", alpha = .5) +
  xlim(1940,2020) +
  ylab("Lexical Diversity (Type-Token Ratio)") +
  xlab("Year")
dev.off()
```

```{r}
male_female_df <- cleaned_df %>%
  filter(gender == "male" | gender == "female")
qqPlot(male_female_df$TTR)
t.test(male_female_df$TTR ~ male_female_df$gender)
```

```{r}
gender_year_df <- cleaned_df %>%
  filter(gender == "male" | gender == "female") %>%
  mutate(year_factor = factor(year), gender = factor(gender)) %>%
  group_by(year_factor, gender) %>%
  summarize(gender_total=n(), sum_TTR=ifelse(gender_total != 0, sum(TTR)/gender_total, 0))  %>%
  mutate(year=as.numeric(as.character(year_factor)))
```

```{r}
pdf(file = "figures/gender-complexity-over-time.pdf", width = 4, height = 3)
ggplot(gender_year_df, aes(x = year, y = sum_TTR, color = gender) ) +
  geom_point() +
  xlim(1940,2020) +
  geom_smooth(method = "gam", alpha = .5, aes(fill = gender)) +
  ylab("Lexical Diversity (Type-Token Ratio)") +
  xlab("Year") + 
  labs(color = "Gender", fill = "Gender") 
# Create one legend https://stackoverflow.com/questions/15370496/ggplot2-draws-two-legends
dev.off()
```

```{r}
anc1 <- lm(TTR ~ gender + year + gender*year, data = male_female_df)
myResPlots2(anc1)
Anova(anc1, type = 3)
summary(anc1)
```

```{r}

tstat_col_caps <- tokens_select(toks, pattern = "^[A-Z]", 
                                valuetype = "regex", 
                                case_insensitive = FALSE, 
                                padding = TRUE)  %>% tokens_remove(c(stopwords("english"))) %>%
                  textstat_collocations(min_count = 10) %>% arrange(-count)
head(tstat_col_caps, 100)

```

